services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: sh -c "if [ ! -f nord_challenge.db ]; then python main.py; fi && uvicorn app.api:app --host localhost --port 8000"
